const auth = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_SIGNUP: 'USER_SIGNUP',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  REFERRAL_CODE: 'REFERRAL_CODE',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  USER_NOT_FOUND: 'User not found',
  NO_INPUT_FOUND: 'No inputs found',
  REF_CODE_NOT_FOUND: 'Referral code not found. Please enter valid code.',
  CREDENTIALS_WRONG: 'Login failed due wrong user credentials',
  USER_DISABLED_BY_ADMIN: 'Your account is disabled by admin. Please contact support team for more information.',
  APP_TYPE_NOT_FOUND: 'App Type not found!',
  LOGIN_SUCCESS_MESSAGE: 'Login successfully',
  SIGNUP_SUCCESS_MESSAGE: 'Signup successfully',
  VERIFY_OTP: 'VERIFY_OTP',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  OTP_MATCHED: 'Otp matched successfully',
  OTP_WRONG: 'Please enter valid otp.',
  OTP_EXPIRE: 'Your entered otp is expired.',
  INVALID_REQUEST: 'Invalid request',
  USER_ALREADY_EXIST: 'User already exist. Please change your mail id',
  ALREADY_REQUESTED: 'You already request for this request. Please check you mail id',
  NOT_REQUESTED_OTP: 'You did not request for reset password. Please enter your email id for received otp',
  NOT_REQUESTED_OTP_FOR_EMAIL: 'You did not request for verify email. Please enter your email id for received otp',
  OTP_SUCCESS_MESSAGE: 'Otp sent to registered email id. Please check you mail id',
  PASSWORD_UPDATE_SUCCESS_MESSAGE: 'Password update successfully',
  EMAIL_VERIFY_SUCCESS_MESSAGE: 'Email verify successfully',
  LOGOUT_SUCCESS_MESSAGE: 'Logout successfully',
  VERIFY_EMAIL_SUB: 'Verify email',
  RESET_PASSWORD_SUB: 'Reset password otp',
  OTP_LIMIT_REACHED: 'Otp request limit exceed',
  VERIFY_EMAIL_TEXT: 'Please click below link to verify your email id.',
};
export default auth;
